name: CI

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: mkdir
        run: mkdir out
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: |
          ./gradlew :app:assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk out/app-debug.apk
      - name: Upload APK(debug)
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: out/app-debug.*

  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: mkdir
        run: mkdir out
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: |
          ./gradlew :app:assembleRelease
          mv app/build/outputs/apk/release/app-release-unsigned.apk out/app-release.apk
      - name: Upload APK(release)
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: out/app-release.*